// © 2026 Alpha - GROUP COMMANDS (CLEAN)
const fs = require("fs");

let dbPath = './database/groupSettings.json';
try {
    if (!fs.existsSync('./database')) fs.mkdirSync('./database', { recursive: true });
    fs.writeFileSync(dbPath, '{}', { flag: 'a' });
} catch {
    dbPath = '/tmp/groupSettings.json';
}

const badWordsPath = './database/badwords.json';
if (!fs.existsSync(badWordsPath)) fs.writeFileSync(badWordsPath, '{}');

const loadSettings = () => { try { if (!fs.existsSync(dbPath)) fs.writeFileSync(dbPath, '{}'); return JSON.parse(fs.readFileSync(dbPath)); } catch { return {}; } };
const saveSettings = (data) => { try { fs.writeFileSync(dbPath, JSON.stringify(data, null, 2)); return true; } catch { return false; } };
const getSettings = (groupId) => { const s = loadSettings(); return s[groupId] || { welcome: false, welcomeMsg: "Welcome @user! 🎉", goodbye: false, goodbyeMsg: "Goodbye @user! 👋", antilink: false, antilinkAction: "delete", antilinkMode: "admins", blockedCountries: [], antiforeign: false, antibot: false }; };
const setSettings = (groupId, data) => { const s = loadSettings(); s[groupId] = { ...getSettings(groupId), ...data }; return saveSettings(s); };
const loadBadWords = () => { try { return JSON.parse(fs.readFileSync(badWordsPath)); } catch { return {}; } };
const saveBadWords = (data) => fs.writeFileSync(badWordsPath, JSON.stringify(data, null, 2));

module.exports = [
    { command: "tagall", execute: async (sock, m, { reply }) => { if (!m.isGroup) return reply("❌ Group only"); if (!m.isAdmin) return reply("❌ Admin only"); try { const meta = await sock.groupMetadata(m.chat); const members = meta.participants; let text = "📢 *Tagging everyone:*\n\n"; for (let mem of members) text += `@${mem.id.split("@")[0]}\n`; await sock.sendMessage(m.chat, { text, mentions: members.map(a => a.id) }, { quoted: m }); } catch { reply("❌ Failed"); } } },
    { command: "kick", execute: async (sock, m, { reply }) => { if (!m.isGroup) return reply("❌ Group only"); if (!m.isAdmin) return reply("❌ Admin only"); let target = m.mentionedJid?.[0] || m.message?.extendedTextMessage?.contextInfo?.mentionedJid?.[0]; if (!target) return reply("❌ Tag someone"); try { await sock.groupParticipantsUpdate(m.chat, [target], "remove"); reply("✅ User kicked"); } catch { reply("❌ Failed"); } } },
    { command: "add", execute: async (sock, m, { args, reply }) => { if (!m.isGroup) return reply("❌ Group only"); if (!m.isAdmin) return reply("❌ Admin only"); if (!args[0]) return reply("❌ Use: .add 123456789"); let number = args[0].replace(/[^0-9]/g, "") + "@s.whatsapp.net"; try { await sock.groupParticipantsUpdate(m.chat, [number], "add"); reply("✅ User added"); } catch { reply("❌ Failed"); } } },
    { command: "promote", execute: async (sock, m, { reply }) => { if (!m.isGroup) return reply("❌ Group only"); if (!m.isAdmin) return reply("❌ Admin only"); let target = m.mentionedJid?.[0] || m.message?.extendedTextMessage?.contextInfo?.mentionedJid?.[0]; if (!target) return reply("❌ Tag someone"); try { await sock.groupParticipantsUpdate(m.chat, [target], "promote"); reply("✅ Promoted"); } catch { reply("❌ Failed"); } } },
    { command: "demote", execute: async (sock, m, { reply }) => { if (!m.isGroup) return reply("❌ Group only"); if (!m.isAdmin) return reply("❌ Admin only"); let target = m.mentionedJid?.[0] || m.message?.extendedTextMessage?.contextInfo?.mentionedJid?.[0]; if (!target) return reply("❌ Tag someone"); try { await sock.groupParticipantsUpdate(m.chat, [target], "demote"); reply("✅ Demoted"); } catch { reply("❌ Failed"); } } },
    { command: "mute", execute: async (sock, m, { reply }) => { if (!m.isGroup) return reply("❌ Group only"); if (!m.isAdmin) return reply("❌ Admin only"); try { await sock.groupSettingUpdate(m.chat, "announcement"); reply("🔇 Group muted"); } catch { reply("❌ Failed"); } } },
    { command: "unmute", execute: async (sock, m, { reply }) => { if (!m.isGroup) return reply("❌ Group only"); if (!m.isAdmin) return reply("❌ Admin only"); try { await sock.groupSettingUpdate(m.chat, "not_announcement"); reply("🔊 Group unmuted"); } catch { reply("❌ Failed"); } } },
    { command: "hidetag", execute: async (sock, m, { args, reply }) => { if (!m.isGroup) return reply("❌ Group only"); if (!m.isAdmin) return reply("❌ Admin only"); try { const meta = await sock.groupMetadata(m.chat); const msg = args.join(" ") || "👀"; await sock.sendMessage(m.chat, { text: msg, mentions: meta.participants.map(p => p.id) }); } catch { reply("❌ Failed"); } } },
    { command: "groupinfo", execute: async (sock, m, { reply }) => { if (!m.isGroup) return reply("❌ Group only"); try { const meta = await sock.groupMetadata(m.chat); reply(`📊 *${meta.subject}*\n👥 ${meta.participants.length} members\n👮 ${meta.participants.filter(p => p.admin).length} admins`); } catch { reply("❌ Failed"); } } },
    { command: "grouplink", execute: async (sock, m, { reply }) => { if (!m.isGroup) return reply("❌ Group only"); if (!m.isAdmin) return reply("❌ Admin only"); try { const code = await sock.groupInviteCode(m.chat); reply(`🔗 https://chat.whatsapp.com/${code}`); } catch { reply("❌ Failed"); } } },
    { command: "revokelink", execute: async (sock, m, { reply }) => { if (!m.isGroup) return reply("❌ Group only"); if (!m.isAdmin) return reply("❌ Admin only"); try { await sock.groupRevokeInvite(m.chat); reply("✅ Link reset"); } catch { reply("❌ Failed"); } } },
    { command: "listadmin", execute: async (sock, m, { reply }) => { if (!m.isGroup) return reply("❌ Group only"); try { const meta = await sock.groupMetadata(m.chat); const admins = meta.participants.filter(p => p.admin); let text = `👑 *Admins (${admins.length})*\n`; for (let a of admins) text += `• @${a.id.split("@")[0]}\n`; await sock.sendMessage(m.chat, { text, mentions: admins.map(a => a.id) }); } catch { reply("❌ Failed"); } } },
    { command: "tagadmin", execute: async (sock, m, { args, reply }) => { if (!m.isGroup) return reply("❌ Group only"); if (!m.isAdmin) return reply("❌ Admin only"); try { const meta = await sock.groupMetadata(m.chat); const admins = meta.participants.filter(p => p.admin); const msg = args.join(" ") || "Attention admins!"; let text = `👑 *${msg}*\n`; for (let a of admins) text += `@${a.id.split("@")[0]} `; await sock.sendMessage(m.chat, { text, mentions: admins.map(a => a.id) }); } catch { reply("❌ Failed"); } } },
    { command: "vcf", execute: async (sock, m, { reply }) => { if (!m.isGroup) return reply("❌ Group only"); try { const meta = await sock.groupMetadata(m.chat); let vcf = ""; for (let p of meta.participants) { let num = p.id.split("@")[0]; vcf += `BEGIN:VCARD\nVERSION:3.0\nFN:${num}\nTEL:${num}\nEND:VCARD\n`; } await sock.sendMessage(m.chat, { document: Buffer.from(vcf), fileName: "contacts.vcf", mimetype: "text/vcard" }); } catch { reply("❌ Failed"); } } },
    { command: "promoteall", execute: async (sock, m, { reply }) => { if (!m.isGroup) return reply("❌ Group only"); if (!m.isAdmin) return reply("❌ Admin only"); try { const meta = await sock.groupMetadata(m.chat); const nonAdmins = meta.participants.filter(p => !p.admin); if (nonAdmins.length === 0) return reply("❌ No members"); reply(`⏳ Promoting ${nonAdmins.length} members...`); for (let p of nonAdmins) { await sock.groupParticipantsUpdate(m.chat, [p.id], "promote"); await new Promise(r => setTimeout(r, 1000)); } reply("✅ Done"); } catch { reply("❌ Failed"); } } },
    { command: "demoteall", execute: async (sock, m, { reply }) => { if (!m.isGroup) return reply("❌ Group only"); if (!m.isAdmin) return reply("❌ Admin only"); try { const meta = await sock.groupMetadata(m.chat); const botId = sock.user.id; const admins = meta.participants.filter(p => p.admin && p.id !== botId); if (admins.length === 0) return reply("❌ No admins"); reply(`⏳ Demoting ${admins.length} admins...`); for (let a of admins) { await sock.groupParticipantsUpdate(m.chat, [a.id], "demote"); await new Promise(r => setTimeout(r, 1000)); } reply("✅ Done"); } catch { reply("❌ Failed"); } } },
    { command: "poll", execute: async (sock, m, { args, reply }) => { if (!m.isGroup) return reply("❌ Group only"); let text = args.join(" "); if (!text.includes("|")) return reply("❌ Format: .poll Question | Option1 | Option2"); let [q, ...opts] = text.split("|").map(s => s.trim()); if (opts.length < 2) return reply("❌ Need 2+ options"); try { await sock.sendMessage(m.chat, { poll: { name: q, values: opts, selectableCount: 1 } }); } catch { reply("❌ Failed"); } } },
    { command: "welcome", execute: async (sock, m, { args, reply }) => { if (!m.isGroup) return reply("❌ Group only"); if (!m.isAdmin) return reply("❌ Admin only"); const action = args[0]?.toLowerCase(); const s = getSettings(m.chat); if (action === "on") { reply(setSettings(m.chat, { welcome: true }) ? "✅ Welcome enabled!" : "❌ Failed"); } else if (action === "off") { reply(setSettings(m.chat, { welcome: false }) ? "❌ Welcome disabled!" : "❌ Failed"); } else { reply(`📊 Welcome: ${s.welcome ? "ON ✅" : "OFF ❌"}\n\n.welcome on/off`); } } },
    { command: "goodbye", execute: async (sock, m, { args, reply }) => { if (!m.isGroup) return reply("❌ Group only"); if (!m.isAdmin) return reply("❌ Admin only"); const action = args[0]?.toLowerCase(); const s = getSettings(m.chat); if (action === "on") { reply(setSettings(m.chat, { goodbye: true }) ? "✅ Goodbye enabled!" : "❌ Failed"); } else if (action === "off") { reply(setSettings(m.chat, { goodbye: false }) ? "❌ Goodbye disabled!" : "❌ Failed"); } else { reply(`📊 Goodbye: ${s.goodbye ? "ON ✅" : "OFF ❌"}\n\n.goodbye on/off`); } } },
    { command: "antilink", execute: async (sock, m, { args, reply }) => { if (!m.isGroup) return reply("❌ Group only"); if (!m.isAdmin) return reply("❌ Admin only"); const action = args[0]?.toLowerCase(); const s = getSettings(m.chat); if (action === "on") { reply(setSettings(m.chat, { antilink: true }) ? "🛡️ Anti-link enabled!" : "❌ Failed"); } else if (action === "off") { reply(setSettings(m.chat, { antilink: false }) ? "❌ Anti-link disabled!" : "❌ Failed"); } else if (action === "delete" || action === "warn" || action === "kick") { reply(setSettings(m.chat, { antilink: true, antilinkAction: action }) ? `🛡️ Anti-link: ${action.toUpperCase()} mode` : "❌ Failed"); } else if (action === "mode") { const mode = args[1]?.toLowerCase(); if (mode === "owner" || mode === "admins") { reply(setSettings(m.chat, { antilinkMode: mode }) ? `👑 Anti-link mode: ${mode.toUpperCase()}` : "❌ Failed"); } else { reply("❌ Use: .antilink mode owner/admins"); } } else { reply(`🛡️ *Anti-Link*\nStatus: ${s.antilink ? "ON ✅" : "OFF ❌"}\nAction: ${s.antilinkAction}\nMode: ${s.antilinkMode || "admins"}\n\n.antilink on/off\n.antilink delete/warn/kick\n.antilink mode owner/admins`); } } },

    //==================== NEW COMMANDS ====================
    { command: "approveall", aliases: ["acceptall"], category: "group", group: true, admin: true, execute: async (sock, m, { reply }) => { if (!m.isAdmin) return reply("❌ Admin only!"); try { const meta = await sock.groupMetadata(m.chat); const requests = meta.joinRequests || []; if (requests.length === 0) return reply("📋 No pending requests!"); reply(`⏳ Approving ${requests.length}...`); let approved = 0; for (let req of requests) { try { await sock.groupRequestApproval(m.chat, req.jid, 'approve'); approved++; } catch {} } reply(`✅ Approved ${approved}/${requests.length}!`); } catch { reply("❌ Feature may not be supported."); } } },
    { command: "kickinactive", aliases: ["inactive"], category: "group", group: true, admin: true, execute: async (sock, m, { reply }) => { if (!m.isAdmin) return reply("❌ Admin only!"); if (!m.isBotAdmin) return reply("❌ Bot must be admin!"); reply("⏳ Removing all non-admin members..."); try { const meta = await sock.groupMetadata(m.chat); let kicked = 0; for (let p of meta.participants) { if (p.admin) continue; try { await sock.groupParticipantsUpdate(m.chat, [p.id], 'remove'); kicked++; await new Promise(r => setTimeout(r, 1000)); } catch {} } reply(`✅ Removed ${kicked} members!`); } catch { reply("❌ Failed!"); } } },
    { command: "antibadword", aliases: ["antibad", "badword"], category: "group", group: true, admin: true, execute: async (sock, m, { args, reply }) => { if (!m.isAdmin) return reply("❌ Admin only!"); const action = args[0]?.toLowerCase(); const word = args.slice(1).join(" "); const bw = loadBadWords(); if (!bw[m.chat]) bw[m.chat] = { enabled: false, words: [] }; if (action === "on") { bw[m.chat].enabled = true; saveBadWords(bw); reply("🛡️ Anti bad word ON!"); } else if (action === "off") { bw[m.chat].enabled = false; saveBadWords(bw); reply("❌ Anti bad word OFF!"); } else if (action === "add" && word) { bw[m.chat].words.push(word.toLowerCase()); saveBadWords(bw); reply(`✅ Added "${word}"`); } else if (action === "remove" && word) { bw[m.chat].words = bw[m.chat].words.filter(w => w !== word.toLowerCase()); saveBadWords(bw); reply(`✅ Removed "${word}"`); } else if (action === "list") { reply(bw[m.chat].words.length === 0 ? "📋 No bad words!" : `🚫 *Bad Words*\n${bw[m.chat].words.map(w => `• ${w}`).join('\n')}`); } else { reply(`🛡️ Anti Bad Word: ${bw[m.chat].enabled ? "ON" : "OFF"}\n\n.antibadword on/off\n.antibadword add [word]\n.antibadword remove [word]\n.antibadword list`); } } },
    { command: "antiforeign", aliases: ["blockcountry"], category: "group", group: true, admin: true, execute: async (sock, m, { args, reply }) => { if (!m.isAdmin) return reply("❌ Admin only!"); if (!m.isBotAdmin) return reply("❌ Bot must be admin!"); const action = args[0]?.toLowerCase(); const s = getSettings(m.chat); if (!s.blockedCountries) s.blockedCountries = []; if (!action) { let text = `🌍 Anti-Foreign: ${s.antiforeign ? "ON" : "OFF"}\n`; if (s.blockedCountries.length > 0) { text += `\n🚫 Blocked:\n`; s.blockedCountries.forEach(c => text += `• +${c}\n`); } return reply(text + `\n.antiforeign +263\n.antiforeign on/off`); } if (action === "on") { setSettings(m.chat, { antiforeign: true }); return reply("🌍 Anti-foreign ON!"); } if (action === "off") { setSettings(m.chat, { antiforeign: false, blockedCountries: [] }); return reply("❌ Anti-foreign OFF!"); } if (action === "list") { return reply(s.blockedCountries.length === 0 ? "📋 No countries blocked!" : `🚫 Blocked: ${s.blockedCountries.map(c => `+${c}`).join(', ')}`); } if (action.startsWith('+')) { const code = action.replace(/[^0-9]/g, ''); if (s.blockedCountries.includes(code)) { s.blockedCountries = s.blockedCountries.filter(c => c !== code); setSettings(m.chat, { blockedCountries: s.blockedCountries }); return reply(`✅ Removed +${code}`); } s.blockedCountries.push(code); setSettings(m.chat, { blockedCountries: s.blockedCountries, antiforeign: true }); reply(`🔄 Blocking +${code}... Kicking members...`); try { const meta = await sock.groupMetadata(m.chat); let kicked = 0; for (let p of meta.participants) { if (p.admin) continue; if (p.id.split('@')[0].startsWith(code)) { try { await sock.groupParticipantsUpdate(m.chat, [p.id], 'remove'); kicked++; await new Promise(r => setTimeout(r, 500)); } catch {} } } reply(`✅ +${code} blocked! Kicked ${kicked} members.`); } catch { reply(`✅ +${code} added to blocked list!`); } } else { reply("❌ Use: .antiforeign +263"); } } },
    { command: "antibot", aliases: ["nobot", "removebot"], category: "group", group: true, admin: true, execute: async (sock, m, { args, reply }) => { if (!m.isAdmin) return reply("❌ Admin only!"); if (!m.isBotAdmin) return reply("❌ Bot must be admin!"); const action = args[0]?.toLowerCase(); if (action === "on") { setSettings(m.chat, { antibot: true }); reply("🤖 Anti-bot ON!"); } else if (action === "off") { setSettings(m.chat, { antibot: false }); reply("❌ Anti-bot OFF!"); } else { reply("🔍 Scanning for bots..."); try { const meta = await sock.groupMetadata(m.chat); let kicked = 0; for (let p of meta.participants) { if (p.id === sock.user.id) continue; const name = (p.name || "").toLowerCase(); if (name.includes('bot') || name.includes('md') || name.includes('wa bot')) { try { await sock.groupParticipantsUpdate(m.chat, [p.id], 'remove'); kicked++; await new Promise(r => setTimeout(r, 500)); } catch {} } } reply(kicked === 0 ? "✅ No bots found!" : `✅ Kicked ${kicked} bots!`); } catch { reply("❌ Scan failed!"); } } } }
];