const fs=require('fs'),ax=require('axios'),yts=require('yt-search'),ytdl=require('@distube/ytdl-core'),{downloadContentFromMessage}=require('@whiskeysockets/baileys'),{execSync}=require('child_process');
const cl=f=>setTimeout(()=>{try{fs.unlinkSync(f)}catch{}},3e5);
const bf=async u=>Buffer.from((await ax.get(u,{responseType:'arraybuffer',timeout:15e3})).data);
const B=c=>({forwardingScore:999,isForwarded:!0,forwardedNewsletterMessageInfo:{newsletterJid:c.newsletter.id+'@newsletter',newsletterName:c.newsletter.name}});

module.exports=[
{command:'play',aliases:['song','music','play2','ytmp3'],category:'downloader',execute:async(s,m,{args,reply,config:c})=>{let t=args.join(' ');if(!t)return reply('❌ Use .play song name');try{await s.sendMessage(m.chat,{react:{text:'🎶',key:m.key}});let sr=await yts(t);if(!sr.videos.length)return reply('❌ No song found');let v=sr.videos[0];const o=`./audio_${Date.now()}.mp3`;await new Promise((res,rej)=>{const st=ytdl(v.url,{quality:'highestaudio',filter:'audioonly'}),w=fs.createWriteStream(o);st.pipe(w);w.on('finish',res);w.on('error',rej);st.on('error',rej)});await s.sendMessage(m.chat,{image:{url:v.thumbnail},caption:`🎵 *${v.title}*\n\n⬇️ Uploading...\n\n👑 ${c.settings.title}`,contextInfo:B(c)},{quoted:m});await s.sendMessage(m.chat,{audio:fs.readFileSync(o),mimetype:'audio/mpeg',ptt:!1,fileName:v.title.replace(/[^a-zA-Z0-9]/g,'_')+'.mp3',contextInfo:{externalAdReply:{title:v.title,body:`🎧 ${c.settings.title}`,thumbnailUrl:v.thumbnail,mediaType:1}}},{quoted:m});await s.sendMessage(m.chat,{react:{text:'✅',key:m.key}});cl(o)}catch(e){console.log('play error:',e.message);reply('❌ Failed')}}},

{command:'video',aliases:['vid','dl','yt','ytmp4'],category:'downloader',execute:async(s,m,{args,reply,config:c})=>{let i=args.join(' ');if(!i)return reply('❌ Provide a link or query!\n📌 .video montreality diamond');let u=i,sr=!1;const YT=/youtube\.com|youtu\.be/.test(i),TT=/tiktok\.com/.test(i),FB=/facebook\.com|fb\.watch/.test(i),IG=/instagram\.com/.test(i),TW=/twitter\.com|x\.com/.test(i),D=YT||TT||FB||IG||TW;if(!D){sr=!0;reply(`🔍 Searching: ${i}`);let r=await yts(i);if(!r.videos?.length)return reply('❌ No results');u=r.videos[0].url;reply(`📹 *${r.videos[0].title}*\n⏳ Downloading...`)}else reply('📹 Downloading...');const o=`./video_${Date.now()}.mp4`;try{await new Promise((res,rej)=>{const st=ytdl(u,{quality:'highest',filter:'audioandvideo'}),w=fs.createWriteStream(o);st.pipe(w);w.on('finish',res);w.on('error',rej);st.on('error',rej)});const stats=fs.statSync(o);if(stats.size>104857600){cl(o);return reply('❌ Video too large (>100MB)')};await s.sendMessage(m.chat,{video:fs.readFileSync(o),mimetype:'video/mp4',fileName:`video_${Date.now()}.mp4`,caption:`✅ Downloaded by Alpha`,contextInfo:B(c)},{quoted:m});cl(o)}catch(e){console.log('video error:',e.message);reply('❌ Failed to download video.')}}},

// ... (keep the rest of the commands: tiktok, gitclone, movie, etc.)
];