// © 2026 Alpha - OWNER COMMANDS (COMPLETE + COMPACT)
const fs=require('fs'),{exec}=require('child_process'),os=require('os'),path=require('path'),clean=j=>j?j.replace(/[^0-9]/g,''):'';
const banPath='./database/banned.json',ownerPath='./database/owners.json';
[banPath,ownerPath].forEach(p=>{if(!fs.existsSync(path.dirname(p)))fs.mkdirSync(path.dirname(p),{recursive:!0});if(!fs.existsSync(p))fs.writeFileSync(p,p.endsWith('banned.json')?'{}':JSON.stringify({tempOwners:[]}))});
const loadBanned=()=>{try{return JSON.parse(fs.readFileSync(banPath))}catch{return{}}},saveBanned=d=>fs.writeFileSync(banPath,JSON.stringify(d,null,2)),loadOwners=()=>{try{return JSON.parse(fs.readFileSync(ownerPath))}catch{return{tempOwners:[]}}},saveOwners=d=>fs.writeFileSync(ownerPath,JSON.stringify(d,null,2));
module.exports=[
{command:"botip",aliases:["serverip","myip","getip"],category:"owner",owner:!0,execute:async(s,m,{reply:r})=>{r("🌐 Fetching...");exec('curl -s ifconfig.me',(e,o)=>{if(e)exec('curl -s ipinfo.io/ip',(e2,o2)=>{if(e2)return r("❌ Could not get IP.");r(`🌐 IP: ${o2.trim()}`)});else r(`🌐 IP: ${o.trim()}`)})}},
{command:"restart",aliases:["reboot","reload"],category:"owner",owner:!0,execute:async(s,m,{reply:r})=>{await r("🔄 Restarting...");setTimeout(()=>process.exit(0),2000)}},
{command:"shutdown",aliases:["stop","kill"],category:"owner",owner:!0,execute:async(s,m,{reply:r})=>{await r("🔴 Shutting down...");setTimeout(()=>process.exit(0),1500)}},
{command:"eval",aliases:[">","exec"],category:"owner",owner:!0,execute:async(s,m,{args:a,reply:r})=>{if(!a[0])return r("❌ Provide code!");try{let res=eval(a.join(" "));if(typeof res==='object')res=JSON.stringify(res,null,2);r(`✅ Result:\n\`\`\`\n${String(res).substring(0,1000)}\n\`\`\``)}catch(e){r(`❌ Error:\n\`\`\`\n${e.message}\n\`\`\``)}}},
{command:"bc",aliases:["broadcast","announce"],category:"owner",owner:!0,execute:async(s,m,{args:a,reply:r})=>{if(!a[0])return r("❌ Provide a message!");let msg=a.join(" "),chats=Object.keys(await s.groupFetchAllParticipating());if(!chats.length)return r("❌ Not in any groups!");r(`📢 Broadcasting to ${chats.length}...`);let ok=0,fail=0;for(let c of chats){try{await s.sendMessage(c,{text:`📢 BROADCAST\n\n${msg}\n\n👑 Owner`});ok++}catch{fail++};await new Promise(r=>setTimeout(r,500))}r(`✅ Sent: ${ok} | Failed: ${fail}`)}},
{command:"bcgc",aliases:["bcgroup","broadcastgc"],category:"owner",owner:!0,execute:async(s,m,{args:a,reply:r})=>{if(!a[0])return r("❌ Provide a message!");let msg=a.join(" "),chats=Object.keys(await s.groupFetchAllParticipating());if(!chats.length)return r("❌ Not in any groups!");r(`📢 Broadcasting to ${chats.length}...`);let ok=0,fail=0;for(let c of chats){try{await s.sendMessage(c,{text:msg});ok++}catch{fail++};await new Promise(r=>setTimeout(r,500))}r(`✅ Sent: ${ok} | Failed: ${fail}`)}},
{command:"join",aliases:["joingroup","enter"],category:"owner",owner:!0,execute:async(s,m,{args:a,reply:r})=>{if(!a[0])return r("❌ Provide a group link!");let code=a[0].split('/').pop().replace(/\?.*/,'');if(!code)return r("❌ Invalid link!");try{let res=await s.groupAcceptInvite(code);r(`✅ Joined group: ${res}`)}catch(e){r(`❌ ${e.message}`)}}},
{command:"leave",aliases:["exit","leavegroup"],category:"owner",owner:!0,execute:async(s,m,{args:a,reply:r})=>{if(!m.isGroup)return r("❌ Works only in groups!");if(a[0]&&a[0].toLowerCase()==='all'){r("⚠️ Leaving all groups...");let chats=Object.keys(await s.groupFetchAllParticipating()),ok=0;for(let c of chats){try{await s.groupLeave(c);ok++;await new Promise(r=>setTimeout(r,500))}catch{}}r(`✅ Left ${ok} groups!`)}else{try{await s.sendMessage(m.chat,{text:"👋 Bot leaving..."});setTimeout(async()=>{await s.groupLeave(m.chat)},1500);r("✅ Leaving group...")}catch(e){r(`❌ ${e.message}`)}}}},
{command:"block",aliases:["blockuser"],category:"owner",owner:!0,execute:async(s,m,{args:a,reply:r,isGroup:g})=>{let t;if(g)t=m.mentionedJid?.[0]||m.quoted?.sender||(a[0]?a[0].replace(/[^0-9]/g,'')+'@s.whatsapp.net':null);else t=m.chat;if(!t||t===s.user.id)return r(!t?"❌ Provide target!":"😂 Can't block self");try{await s.updateBlockStatus(t,"block");r(`🚫 Blocked @${t.split('@')[0]}`)}catch(e){r(`❌ ${e.message}`)}}},
{command:"unblock",aliases:["unblockuser"],category:"owner",owner:!0,execute:async(s,m,{args:a,reply:r,isGroup:g})=>{let t;if(g)t=m.mentionedJid?.[0]||m.quoted?.sender||(a[0]?a[0].replace(/[^0-9]/g,'')+'@s.whatsapp.net':null);else t=m.chat;if(!t)return r("❌ Provide target!");try{await s.updateBlockStatus(t,"unblock");r(`✅ Unblocked @${t.split('@')[0]}`)}catch(e){r(`❌ ${e.message}`)}}},
{command:"blocklist",aliases:["listblock","blocks"],category:"owner",owner:!0,execute:async(s,m,{reply:r})=>{try{let blocked=await s.fetchBlocklist();if(!blocked.length)return r("📋 No blocked users.");let txt=`🚫 BLOCKED (${blocked.length})\n\n`;for(let u of blocked)txt+=`• @${u.split('@')[0]}\n`;await s.sendMessage(m.chat,{text:txt,mentions:blocked})}catch(e){r(`❌ ${e.message}`)}}},
{command:"pm",aliases:["msg","send"],category:"owner",owner:!0,execute:async(s,m,{args:a,reply:r})=>{if(!a[0])return r("❌ .pm <number> <message>");let num=a[0].replace(/[^0-9]/g,''),msg=a.slice(1).join(" ");if(!msg)return r("❌ Provide message!");try{await s.sendMessage(num+'@s.whatsapp.net',{text:`📨 Owner Message:\n\n${msg}`});r(`✅ Sent to ${num}`)}catch(e){r(`❌ ${e.message}`)}}},
{command:"banuser",aliases:["ban"],category:"owner",owner:!0,execute:async(s,m,{args:a,reply:r})=>{let t=m.mentionedJid?.[0]||(a[0]?a[0].replace(/[^0-9]/g,'')+'@s.whatsapp.net':null)||m.quoted?.sender;if(!t)return r("❌ Provide target!");let ban=loadBanned();ban[clean(t)]={jid:t,date:new Date().toISOString()};saveBanned(ban);r(`🚫 Banned @${t.split('@')[0]}`)}},
{command:"unbanuser",aliases:["unban"],category:"owner",owner:!0,execute:async(s,m,{args:a,reply:r})=>{let t=m.mentionedJid?.[0]||(a[0]?a[0].replace(/[^0-9]/g,'')+'@s.whatsapp.net':null)||m.quoted?.sender;if(!t)return r("❌ Provide target!");let ban=loadBanned(),num=clean(t);if(ban[num]){delete ban[num];saveBanned(ban);r(`✅ Unbanned @${t.split('@')[0]}`)}else r("❌ Not banned.")}},
{command:"banlist",aliases:["banned","listban"],category:"owner",owner:!0,execute:async(s,m,{reply:r})=>{let ban=loadBanned(),users=Object.values(ban);if(!users.length)return r("📋 No banned users.");let txt=`🚫 BANNED (${users.length})\n\n`,mentions=[];for(let u of users){txt+=`• @${u.jid.split('@')[0]}\n`;mentions.push(u.jid)}await s.sendMessage(m.chat,{text:txt,mentions})}},
{command:"addowner",aliases:["addown"],category:"owner",owner:!0,execute:async(s,m,{args:a,reply:r})=>{let t=m.mentionedJid?.[0]||(a[0]?a[0].replace(/[^0-9]/g,'')+'@s.whatsapp.net':null)||m.quoted?.sender;if(!t)return r("❌ Provide target!");let owners=loadOwners(),num=clean(t);if(!owners.tempOwners.includes(num)){owners.tempOwners.push(num);saveOwners(owners);r(`👑 Owner added @${t.split('@')[0]}`)}else r("❌ Already owner.")}},
{command:"delowner",aliases:["removeowner","delown"],category:"owner",owner:!0,execute:async(s,m,{args:a,reply:r})=>{let t=m.mentionedJid?.[0]||(a[0]?a[0].replace(/[^0-9]/g,'')+'@s.whatsapp.net':null)||m.quoted?.sender;if(!t)return r("❌ Provide target!");let owners=loadOwners(),num=clean(t),idx=owners.tempOwners.indexOf(num);if(idx>-1){owners.tempOwners.splice(idx,1);saveOwners(owners);r(`✅ Owner removed @${t.split('@')[0]}`)}else r("❌ Not an owner.")}},
{command:"owners",aliases:["listowner","ownerlist"],category:"owner",owner:!0,execute:async(s,m,{reply:r,config:cfg})=>{let owners=loadOwners(),txt=`👑 OWNERS\n\n🔷 Main: ${cfg.owner.join(', ')}\n`;if(owners.tempOwners.length){txt+=`\n🔶 Temp:\n`;for(let o of owners.tempOwners)txt+=`• ${o}\n`}r(txt)}},
{command:"getchannel",aliases:["channeljid","cjid"],category:"owner",owner:!0,execute:async(s,m,{args:a,reply:r})=>{if(!a[0])return r("❌ Provide channel link!");let m2=a[0].match(/channel\/([^\/\?]+)/);if(!m2)return r("❌ Invalid link!");let jid=m2[1]+'@newsletter';r(`✅ Channel JID: \`${jid}\``)}},
{command:"mychannels",aliases:["channels","listchannels"],category:"owner",owner:!0,execute:async(s,m,{reply:r})=>{r("📰 Use .getchannel <link> to get channel JID.")}},
// --- MISSING COMMANDS ---
{command:"anticall",aliases:["rejectcall","callblocker"],category:"owner",owner:!0,execute:async(s,m,{args:a,reply:r})=>{let p='./database/anticall.json';if(!fs.existsSync(p))fs.writeFileSync(p,'{"enabled":false}');let c=a[0]?.toLowerCase();if(c==='on'){fs.writeFileSync(p,'{"enabled":true}');r('📵 Anti‑Call ON')}else if(c==='off'){fs.writeFileSync(p,'{"enabled":false}');r('✅ Anti‑Call OFF')}else r(`📵 Anti‑Call: ${JSON.parse(fs.readFileSync(p)).enabled?'ON':'OFF'}\n.anticall on/off`)}},
{command:"autoreply",aliases:["setautoreply","ar"],category:"owner",owner:!0,execute:async(s,m,{args:a,reply:r})=>{let p='./database/autoreply.json';if(!fs.existsSync(p))fs.writeFileSync(p,'{"enabled":false,"message":"Busy, will reply later."}');let c=a[0]?.toLowerCase();if(c==='on'){let d=JSON.parse(fs.readFileSync(p));d.enabled=!0;if(a[1])d.message=a.slice(1).join(' ');fs.writeFileSync(p,JSON.stringify(d));r(`💬 Auto‑Reply ON\nMsg: ${d.message}`)}else if(c==='off'){let d=JSON.parse(fs.readFileSync(p));d.enabled=!1;fs.writeFileSync(p,JSON.stringify(d));r('🔇 Auto‑Reply OFF')}else{let d=JSON.parse(fs.readFileSync(p));r(`💬 Auto‑Reply: ${d.enabled?'ON':'OFF'}\nMsg: ${d.message}\nUse: .autoreply on/off <message>`)}}},
{command:"hack",aliases:["prank"],category:"owner",owner:!0,execute:async(s,m,{args:a,reply:r})=>{let t=m.mentionedJid?.[0]||m.quoted?.sender||(a[0]?a[0].replace(/[^0-9]/g,'')+'@s.whatsapp.net':null);if(!t)return r('❌ Mention or reply');let n=t.split('@')[0],steps=[`🔍 Hacking ${n}... 0%`,`🛰️ Satellite... 20%`,`🔓 Bypass... 40%`,`📡 Trojan... 60%`,`🗂️ Downloading... 80%`,`✅ ${n} hacked! Just kidding 😂`];for(let i of steps){await s.sendMessage(m.chat,{text:i},{quoted:m});await new Promise(res=>setTimeout(res,1500))}}},
{command:"poststatus",aliases:["setstatus"],category:"owner",owner:!0,execute:async(s,m,{args:a,reply:r})=>{try{if(m.quoted){let msg=m.quoted,buf=await s.downloadMediaMessage(msg),type=Object.keys(msg.message)[0];if(type==='imageMessage'||type==='videoMessage'){await s.sendMessage('status@broadcast',{[type==='imageMessage'?'image':'video']:buf,caption:a.join(' ')||''});r('✅ Status posted!')}else r('❌ Unsupported')}else{if(!a[0])return r('❌ Provide text');await s.sendMessage('status@broadcast',{text:a.join(' ')});r('✅ Status posted!')}}catch(e){r(`❌ ${e.message}`)}}},
{command:"cleartmp",aliases:["cleartemp"],category:"owner",owner:!0,execute:async(s,m,{reply:r})=>{try{let tmp=os.tmpdir(),rem=0;if(fs.existsSync(tmp)){let files=fs.readdirSync(tmp);for(let f of files){if(f.startsWith('pair_')||f.startsWith('alpha_pair_')){try{fs.rmSync(path.join(tmp,f),{recursive:!0,force:!0});rem++}catch{}}}}r(`🧹 Cleaned ${rem} temp files.`)}catch(e){r(`❌ ${e.message}`)}}},
{command:"autosticker",aliases:["autos"],category:"owner",owner:!0,execute:async(s,m,{args:a,reply:r})=>{let p='./database/autosticker.json';if(!fs.existsSync(p))fs.writeFileSync(p,'{"enabled":false}');let c=a[0]?.toLowerCase();if(c==='on'){fs.writeFileSync(p,'{"enabled":true}');r('🖼️ Auto‑Sticker ON')}else if(c==='off'){fs.writeFileSync(p,'{"enabled":false}');r('❌ Auto‑Sticker OFF')}else r(`🖼️ Auto‑Sticker: ${JSON.parse(fs.readFileSync(p)).enabled?'ON':'OFF'}\n.autosticker on/off`)}},
{command:"autovoice",aliases:["autovn"],category:"owner",owner:!0,execute:async(s,m,{args:a,reply:r})=>{let p='./database/autovoice.json';if(!fs.existsSync(p))fs.writeFileSync(p,'{"enabled":false}');let c=a[0]?.toLowerCase();if(c==='on'){fs.writeFileSync(p,'{"enabled":true}');r('🎤 Auto‑Voice ON')}else if(c==='off'){fs.writeFileSync(p,'{"enabled":false}');r('❌ Auto‑Voice OFF')}else r(`🎤 Auto‑Voice: ${JSON.parse(fs.readFileSync(p)).enabled?'ON':'OFF'}\n.autovoice on/off`)}},
{command:"dmblocker",aliases:["antidm","blockdm"],category:"owner",owner:!0,execute:async(s,m,{args:a,reply:r})=>{let p='./database/dmblocker.json';if(!fs.existsSync(p))fs.writeFileSync(p,'{"enabled":false}');let c=a[0]?.toLowerCase();if(c==='on'){fs.writeFileSync(p,'{"enabled":true}');r('🚫 DM Blocker ON. Only owners can DM.')}else if(c==='off'){fs.writeFileSync(p,'{"enabled":false}');r('✅ DM Blocker OFF')}else r(`🚫 DM Blocker: ${JSON.parse(fs.readFileSync(p)).enabled?'ON':'OFF'}\n.dmblocker on/off`)}},
{command:"antispam",aliases:["spamfilter"],category:"owner",owner:!0,execute:async(s,m,{args:a,reply:r})=>{let p='./database/antispam.json';if(!fs.existsSync(p))fs.writeFileSync(p,'{"enabled":false,"threshold":5000}');let c=a[0]?.toLowerCase();if(c==='on'){let d=JSON.parse(fs.readFileSync(p));d.enabled=!0;fs.writeFileSync(p,JSON.stringify(d));r('🛡️ Anti‑Spam ON (5s)')}else if(c==='off'){let d=JSON.parse(fs.readFileSync(p));d.enabled=!1;fs.writeFileSync(p,JSON.stringify(d));r('❌ Anti‑Spam OFF')}else{let d=JSON.parse(fs.readFileSync(p));r(`🛡️ Anti‑Spam: ${d.enabled?'ON':'OFF'}\nThreshold: ${d.threshold}ms\n.antispam on/off`)}}}
];